#!/bin/bash
max=128
help_make_begin_require(){
	if [ $1 = $max ] ; then
		echo '#error "Too many levels of require"'
	else
		echo "#ifdef _EOC_require_$1_"
		local k=$1
		let k++
		help_make_begin_require $k
		echo "#else"
		echo "#define _EOC_require_$1_"
		echo "#endif"
	fi
}
make_begin_require(){
	echo "//generated by make.sh"
	echo "#ifdef _EOC_require_"
	help_make_begin_require 0
	echo "#else"
	echo "#define _EOC_require_"
	echo "#endif"
	cat prelude.h
}
help_make_end_require(){
	if [ $1 = $max ] ; then
		echo "#ifdef _EOC_require_$1_"
		echo '#error "BUG!"'
		echo "#else"
		echo "#undef $2"
		echo "#endif"
	else
		echo "#ifdef _EOC_require_$1_"
		local k=$1
		let k++
		help_make_end_require $k "_EOC_require_$1_"
		echo "#else"
		echo "#undef $2"
		echo "#endif"
	fi
}
make_end_require(){
	echo "//generated by make.sh"
	echo "#ifdef _EOC_require_"
	help_make_end_require 0 _EOC_require_
	echo "#else"
	echo '#error "Too many >require"'
	echo "#endif"
	cat prelude.h
}
make_begin_require > 'require<'
make_end_require > '>require'
echo "//generated by make.sh" > 'module<'
cat prelude.h >> 'module<'
echo "//generated by make.sh" > '>module'
