#!/bin/bash
max=128
help_make_begin_require(){
	if [ $1 = $max ] ; then
		echo '#error "Too many levels of require"'
	else
		echo "#ifdef EOC_require_$1"
		local k=$1
		let k++
		help_make_begin_require $k
		echo "#else"
		echo "#define EOC_require_$1"
		echo "#endif"
	fi
}
make_begin_require(){
	echo "//generated by make.sh"
	echo "#ifdef EOC_require"
	help_make_begin_require 0
	echo "#else"
	echo "#define EOC_require"
	echo "#endif"
	cat lang.h
}
help_make_end_require(){
	if [ $1 = $max ] ; then
		echo "#ifdef EOC_require_$1"
		echo '#error "BUG!"'
		echo "#else"
		echo "#undef $2"
		echo "#endif"
	else
		echo "#ifdef EOC_require_$1"
		local k=$1
		let k++
		help_make_end_require $k "EOC_require_$1"
		echo "#else"
		echo "#undef $2"
		echo "#endif"
	fi
}
make_end_require(){
	echo "//generated by make.sh"
	echo "#ifdef EOC_require"
	help_make_end_require 0 EOC_require
	echo "#else"
	echo '#error "Too many >require"'
	echo "#endif"
	cat lang.h
}
make_begin_require > 'require<'
make_end_require > '>require'
echo "//generated by make.sh" > 'module<'
cat lang.h >> 'module<'
echo "//generated by make.sh" > '>module'
