#!/bin/bash
#    Copyright (C) 2018  Zaoqi

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published
#    by the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.

#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
max=128
help_make_begin_require(){
	if [ $1 = $max ] ; then
		echo '#error "Too many levels of require"'
	else
		echo "#ifdef EOC_require_$1"
		local k=$1
		let k++
		help_make_begin_require $k
		echo "#else"
		echo "#define EOC_require_$1"
		echo "#endif"
	fi
}
make_begin_require(){
	echo "/* generated by https://github.com/zaoqi/Expression-Oriented-C/blob/master/make.sh */"
	echo "#ifdef EOC_require"
	help_make_begin_require 0
	echo "#else"
	echo "#define EOC_require"
	echo "#endif"
	echo '#include "module<"'
}
help_make_end_require(){
	if [ $1 = $max ] ; then
		echo "#ifdef EOC_require_$1"
		echo '#error "BUG!"'
		echo "#else"
		echo "#undef $2"
		echo "#endif"
	else
		echo "#ifdef EOC_require_$1"
		local k=$1
		let k++
		help_make_end_require $k "EOC_require_$1"
		echo "#else"
		echo "#undef $2"
		echo "#endif"
	fi
}
make_end_require(){
	echo "/* generated by https://github.com/zaoqi/Expression-Oriented-C/blob/master/make.sh */"
	echo "#ifdef EOC_require"
	help_make_end_require 0 EOC_require
	echo "#else"
	echo '#error "Too many >require"'
	echo "#endif"
	echo '#include "module<"'
}
make_begin_require > 'require<'
make_end_require > '>require'
echo "/* generated by https://github.com/zaoqi/Expression-Oriented-C/blob/master/make.sh */" > 'module<'
./make_macro_tools.sh >> 'module<'
cat lang.h >> 'module<'
echo "/* generated by https://github.com/zaoqi/Expression-Oriented-C/blob/master/make.sh */" > '>module'
