#undef make_void
#undef define_type
#undef int8
#undef int16
#undef int32
#undef int64
#undef int_pointer
#undef nat8
#undef nat16
#undef nat32
#undef nat64
#undef nat_pointer
#undef byte
#undef signed_byte
#undef restrict
#undef cast
#undef annotate
#undef bool_not
#undef eq_p
#undef not_eq_p
#undef bool_and
#undef bool_or
