#undef make_void
#undef define_type
#undef int8
#undef int16
#undef int32
#undef int64
#undef int_pointer
#undef nat8
#undef nat16
#undef nat32
#undef nat64
#undef nat_pointer
#undef byte
#undef signed_byte
#undef restrict
#undef cast
#undef annotate
#undef bool_not
#undef eq_p
#undef not_eq_p
#undef bool_and
#undef bool_or
#undef anonymous_struct
#undef declare_struct
#undef define_struct
#undef anonymous_union
#undef declare_union
#undef define_union
#undef anonymous_enumeration
#undef declare_enumeration
#undef define_enumeration
#ifndef __cplusplus
#undef bool
#endif
#ifndef __cplusplus
#undef true
#endif
#ifndef __cplusplus
#undef false
#endif
